version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "5000"

  proxy:
    build:
      context: ./conf
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - "app"